# Advanced 11 — Compliance, Audit & Forensic Readiness for Agent Identity

## Scenario

Northstar Insurance is preparing its 2026-Q3 assurance package for production claims agents. We will replace a self-reported posture checklist with a deterministic, evidence-backed assessment whose audit pack can be verified independently.

![Compliance, audit, and forensic readiness lifecycle](images/compliance-audit-forensic-readiness.png)

**Success criteria:** valid controls have complete, current, authentic evidence; exceptions remain visible; missing or untrusted evidence routes to review; critical failures block; signed packs detect edits and truncation.

**Safety boundary:** all identities, keys, events, and incidents are synthetic. The notebook is offline and does not certify compliance or provide legal advice.

## 1. Reproducible environment

The notebook imports the exact `lab.py` module exercised by the test suite. The fixed assessment time makes freshness, expiry, sampling, and evaluation deterministic.

In [1]:
# Reusable implementation: lab.py
from datetime import timedelta
from pathlib import Path
import json
import pandas as pd
import lab

print({"assessment_time": lab.NOW.isoformat(), "tenant": lab.TENANT, "policy": lab.CONTROL_CATALOG_VERSION})

{'assessment_time': '2026-10-28T12:00:00+00:00', 'tenant': 'northstar-insurance', 'policy': 'northstar-agent-identity-2026.10'}

## 2. Establish the weak baseline

The baseline trusts inventory fields. It has no source authentication, evidence completeness, freshness, replay defense, exception semantics, or independent verification. We measure it before adding controls so improvement is observable rather than asserted.

In [2]:
initial = lab.evaluation()
pd.DataFrame([initial["baseline"], initial["hardened"]], index=["self-reported baseline", "evidence-backed"])

                        exact  total  accuracy  false_passes  false_blocks
self-reported baseline      9     18       0.5             8             0
evidence-backed            18     18       1.0             0             0

The baseline classifies only 9/18 cases exactly and releases eight cases that should block or require review. A high pass rate is therefore not an assurance metric.

## 3. Version the control catalog and mappings

Control requirements name evidence types and freshness limits. Framework mappings are traceability aids—not claims that one technical test proves an entire regulatory obligation.

In [3]:
catalog = pd.DataFrame([c.model_dump(mode="json") for c in lab.CONTROL_CATALOG])
catalog[["control_id", "name", "critical", "evidence_types", "max_age_hours"]]

,control_id,name,critical,evidence_types,max_age_hours
0,AG-01,Registered agent identity,True,[registry_record],24
1,AG-02,Named accountable owner,True,[owner_record],24
2,CR-01,Short-lived production credential,True,"[credential_config, issuance_event]",24
3,AC-01,Least privilege,False,"[entitlement_snapshot, usage_window]",168
4,DG-01,Delegation attenuation,True,"[delegation_record, policy_decision]",24
5,LC-01,Complete offboarding,True,"[lifecycle_event, revocation_event]",24
6,AU-01,Critical action reconstruction,True,"[authorization_event, enforcement_event, actio...",24

Mappings must carry a framework version and primary source. This prevents a silent mapping drift when a catalog, regulation, or assessment procedure changes.

In [4]:
mapping_rows = [
    {"control_id": control_id, **mapping.model_dump(mode="json")}
    for control_id, mappings in lab.FRAMEWORK_MAPPINGS.items()
    for mapping in mappings
]
pd.DataFrame(mapping_rows)[["control_id", "framework", "version", "references"]]

,control_id,framework,version,references
0,AG-01,NIST SP 800-53,5.2.0,"[IA-4, CM-8]"
1,AG-01,CIS Controls,8.1,[5.1]
2,CR-01,NIST SP 800-53,5.2.0,"[IA-5, AC-2]"
3,AU-01,NIST SP 800-53,5.2.0,"[AU-2, AU-3, AU-10, AU-12]"
4,AU-01,EU AI Act,Regulation (EU) 2024/1689,[Article 12]

## 4. Load the scoped inventory through strict contracts

Schema-valid data is still untrusted, but rejecting unknown fields and cross-tenant records reduces ambiguity before assessment.

In [5]:
inventory_path = Path("data/agent_inventory.json")
inventory = [lab.AgentRecord.model_validate(item) for item in json.loads(inventory_path.read_text())]
pd.DataFrame([a.model_dump(mode="json") for a in inventory])[["agent_id", "environment", "risk", "active", "credential_type"]]

         agent_id environment      risk  active credential_type
0    agent:claims        prod      high    True        workload
1  agent:research        prod  critical    True        workload
2    agent:legacy        prod      high    True  static_api_key
3   agent:retired        prod    medium   False            none

## 5. Admit signed evidence at a trusted boundary

An evidence artifact is accepted only when its tenant, source-to-producer binding, payload digest, signature, observation time, collection time, and replay state are valid.

In [6]:
claims = inventory[0]
artifacts = lab.evidence_for_agent(claims)
store = lab.EvidenceStore()
admitted = [store.admit(item) for item in artifacts]
{"offered": len(artifacts), "admitted": sum(admitted), "rejections": store.rejections}

{'offered': 9, 'admitted': 9, 'rejections': []}

The evidence IDs are stable references. Results cite those IDs rather than embedding mutable screenshots or treating a source name as proof.

In [7]:
results = [lab.evaluate_control(control, claims, store) for control in lab.CONTROL_CATALOG]
result_frame = pd.DataFrame([r.model_dump(mode="json") for r in results])
result_frame[["control_id", "status", "reason_code", "evidence_complete", "evidence_ids"]]

,control_id,status,reason_code,evidence_complete,evidence_ids
0,AG-01,pass,registered,True,[ev-claims-1]
1,AG-02,pass,owner-present,True,[ev-claims-2]
2,CR-01,pass,credential-compliant,True,"[ev-claims-3, ev-claims-4]"
3,AC-01,pass,least-privilege,True,"[ev-claims-5, ev-claims-6]"
4,DG-01,not_applicable,control-not-applicable,True,[]
5,LC-01,not_applicable,control-not-applicable,True,[]
6,AU-01,pass,critical-action-recorded,True,"[ev-claims-7, ev-claims-8, ev-claims-9]"

## 6. Make completeness measurable

Completeness is `controls with all required fresh evidence / applicable controls`. Not-applicable controls are excluded, and indeterminate is never converted to pass.

In [8]:
coverage = lab.completeness(results)
assert coverage == {"complete": 5, "relevant": 5, "ratio": 1.0}
coverage

{'complete': 5, 'relevant': 5, 'ratio': 1.0}

## 7. Failure injection: forged evidence

Changing a signature is rejected before the artifact can influence a control result.

In [9]:
forged = artifacts[0].model_copy(update={"signature": lab.b64(b"x" * 64)})
forged_store = lab.EvidenceStore()
assert not forged_store.admit(forged)
forged_store.rejections

[('ev-claims-1', 'invalid-signature')]

## 8. Failure injection: missing evidence

Dropping one required action event makes the audit control indeterminate and routes the release decision to review.

In [10]:
missing_results, _ = lab.assess_agent(claims, artifacts=artifacts[:-1])
[(r.control_id, r.status, r.reason_code) for r in missing_results if r.status == "indeterminate"], lab.release_decision(missing_results)

([('AU-01', 'indeterminate', 'missing-evidence')], 'review')

## 9. Failure injection: stale evidence

An old signed artifact may be authentic but no longer adequate for a freshness-bounded control.

In [11]:
stale = artifacts[0].model_copy(update={"effective_at": lab.NOW - timedelta(days=4)})
lab.required_evidence(lab.CONTROL_BY_ID["AG-01"], [stale])

((), False, 'missing-evidence')

## 10. Exceptions remain visible

A valid exception is bound to tenant, subject, control, trusted approver, validity interval, state, rationale, and required compensating controls. It routes to review and never becomes pass.

In [12]:
legacy = inventory[2]
exception = lab.approved_exception()
legacy_results, _ = lab.assess_agent(legacy, exceptions=[exception])
credential_result = next(r for r in legacy_results if r.control_id == "CR-01")
credential_result.model_dump(mode="json"), lab.release_decision(legacy_results)

({'control_id': 'CR-01',
  'subject': 'agent:legacy',
  'status': 'exception',
  'reason_code': 'approved-bounded-exception',
  'tested_at': '2026-10-28T12:00:00Z',
  'policy_version': 'northstar-agent-identity-2026.10',
  'evidence_ids': ['ev-legacy-3', 'ev-legacy-4'],
  'evidence_complete': True,
  'critical': True,
  'exception_id': 'EX-12'},
 'review')

Expired or undercompensated exceptions fail closed. The underlying technical failure remains; governance decides whether a bounded exception is acceptable.

In [13]:
expired = lab.approved_exception(expires_at=lab.NOW - timedelta(seconds=1))
undercompensated = lab.approved_exception(compensating_controls=frozenset({"vault"}))
[
    lab.valid_exception(item, control_id="CR-01", subject="agent:legacy")
    for item in (expired, undercompensated)
]

[(False, 'exception-expired-or-not-yet-valid'),
 (False, 'compensating-controls-incomplete')]

## 11. Delegation and offboarding invariants

Delegated authority must be a subset of parent authority. Inactive identities are assessed against offboarding completeness rather than active credential posture.

In [14]:
widened = lab.agent_fixture(
    delegated_parent=frozenset({"documents.read"}),
    delegated_child=frozenset({"documents.read", "claims.write"}),
)
widened_results, _ = lab.assess_agent(widened)
[(r.control_id, r.status, r.reason_code) for r in widened_results if r.status == "fail"]

[('DG-01', 'fail', 'delegation-widened')]

The retired agent has only the lifecycle control in scope; complete revocation is required for release.

In [15]:
retired = inventory[3]
retired_results, _ = lab.assess_agent(retired)
[(r.control_id, r.status) for r in retired_results], lab.release_decision(retired_results)

([('AG-01', 'not_applicable'),
  ('AG-02', 'not_applicable'),
  ('CR-01', 'not_applicable'),
  ('AC-01', 'not_applicable'),
  ('DG-01', 'not_applicable'),
  ('LC-01', 'pass'),
  ('AU-01', 'not_applicable')],
 'release')

## 12. Inspect segregation of duties as a graph

The graph makes principal-permission relationships observable and detects a principal holding both create and approve authority.

In [16]:
sod = lab.segregation_of_duties(
    {
        "team:builder": {"agent.create"},
        "team:reviewer": {"agent.approve"},
        "team:admin": {"agent.create", "agent.approve"},
    },
    [("agent.create", "agent.approve")],
)
sod

{'conflicts': [{'principal': 'team:admin',
   'permissions': ('agent.approve', 'agent.create')}],
 'principals': 3,
 'permissions': 2,
 'edges': 4}

## 13. Risk-based sampling with an explicit denominator

Sampling never proves whole-population compliance. We record the population, sample size, risk distribution, and critical-agent coverage so reviewers can see selection risk.

In [17]:
population = [
    lab.agent_fixture(f"agent:sample-{i}", risk=("critical" if i < 5 else "high" if i < 15 else "low"))
    for i in range(40)
]
sample = lab.risk_sample(population, 12, seed=42)
[item.agent_id for item in sample]

['agent:sample-6',
 'agent:sample-33',
 'agent:sample-4',
 'agent:sample-24',
 'agent:sample-0',
 'agent:sample-5',
 'agent:sample-14',
 'agent:sample-11',
 'agent:sample-38',
 'agent:sample-2',
 'agent:sample-28',
 'agent:sample-8']

The fixed seed makes the teaching experiment reproducible. Production sampling must record rationale, exclusions, and population lineage.

In [18]:
sample_report = lab.sample_coverage(population, sample)
assert sample_report["population"] == 40 and sample_report["sample"] == 12
sample_report

{'population': 40,
 'sample': 12,
 'population_by_risk': {'critical': 5, 'high': 10, 'low': 25},
 'sample_by_risk': {'high': 5, 'low': 4, 'critical': 3},
 'critical_coverage': 0.6}

## 14. Build a chain of custody

Each entry binds the previous hash. Internal verification detects edits and reordering, but a shortened prefix still looks internally valid; the signed audit pack must bind the expected terminal root.

In [19]:
custody = lab.build_custody([
    {
        "artifact_id": item.artifact_id,
        "actor": "collector:assurance",
        "action": "collected",
        "occurred_at": lab.NOW - timedelta(minutes=2),
    }
    for item in store.artifacts.values()
])
{"entries": len(custody), "verified": lab.verify_custody(custody), "root": custody[-1].entry_hash}

{'entries': 9,
 'verified': True,
 'root': 'b81ad3c950b8237290c6f8d66b6b2a2c5ac7bf7e70d5d2c74a80239b47bb0274'}

Editing an earlier actor breaks that entry and every later link.

In [20]:
edited_custody = list(custody)
edited_custody[0] = edited_custody[0].model_copy(update={"actor": "attacker"})
assert not lab.verify_custody(edited_custody)
lab.verify_custody(edited_custody)

False

## 15. Retention and legal hold

Normal retention may delete old evidence. An active, tenant-bound legal hold overrides deletion until formally released.

In [21]:
old_artifact = artifacts[0].model_copy(update={"effective_at": lab.NOW - timedelta(days=400)})
hold = lab.LegalHold(
    hold_id="LH-44", tenant=lab.TENANT, case_id="IR-2026-17",
    artifact_ids=frozenset({old_artifact.artifact_id}), issued_by="legal:counsel",
    issued_at=lab.NOW - timedelta(days=2),
)
lab.retention_action(old_artifact, retention_days=365, holds=[hold])

'retain'

## 16. Sign the audit pack

The pack binds the scope, result set, complete artifact ID/digest set, artifact count, custody root, legal holds, catalog version, mapping version, period, and signer.

In [22]:
signer = lab.deterministic_private_key("audit-office")
pack = lab.build_audit_pack(
    [claims], results, store.artifacts.values(), custody, [hold], signer=signer
)
pack.model_dump(mode="json")

{'pack_id': 'pack-2026-q3',
 'tenant': 'northstar-insurance',
 'period': '2026-Q3',
 'catalog_version': 'northstar-agent-identity-2026.10',
 'mapping_version': '2026.10',
 'created_at': '2026-10-28T12:00:00Z',
 'scope_digest': 'be90251b0fe8e53d5f39a8522a36281f2f3eb8d6ae68d0565d13f2fd41710724',
 'result_digest': '14de5991b5e18853ad4269db5bfec0e1da4fec467d6d6e991a795207ce75ddb1',
 'artifact_digests': [['ev-claims-1',
   '10cdbb9b835928963ec6ecbbed2cb32d4244b40a3f12f103ee6a6b83c773d144'],
  ['ev-claims-2',
   '20e22513a2a2db2420778ef9d04f441e75c257c788c0f38e98898e0460c254c3'],
  ['ev-claims-3',
   'ffca0894afc2bd7c75dd9bd4a62345b02b1f9083da8ebe977dccfafb17287621'],
  ['ev-claims-4',
   '4f040e709f424d14469b2f663ea82deb31f470fb928b7241126159709c9724e1'],
  ['ev-claims-5',
   '3589ca2574760f443843071d6c6904ea7681f6c6d99ac51c63834a6b3a204fa3'],
  ['ev-claims-6',
   'ec0d801d63f009e0acdfa01c7668b90079abbb1aed7d1995d9bd22ed1185c96d'],
  ['ev-claims-7',
   '653901dd3358823fd9253102bef0f6074e2164db955cc8d99dee9b831ae324ff'],
  ['ev-claims-8',
   '5f022fec3403ca8ea10d014a3441598aca1c501115e7c7c1356c6469bcf503db'],
  ['ev-claims-9',
   'e8de58da3ae4e2aa70f27e3884fc92e97aa13b3f66e6c50f8181844398e581e5']],
 'artifact_count': 9,
 'custody_root': 'b81ad3c950b8237290c6f8d66b6b2a2c5ac7bf7e70d5d2c74a80239b47bb0274',
 'legal_hold_ids': ['LH-44'],
 'manifest_digest': '426a4e809e839f328db25e4102272fc79e4eead1d3001f40afe2654ec74cda93',
 'signature': 'ZDURrC6DgqxilRbTGcJv7u54xJ/Sd4gNeZAqie2rCs2tWZK/tJKnRJdezof3tdjJ+XbQadVxRqd22N7xDG4rCw=='}

An independent verifier receives the public key and the actual scope, results, artifacts, and custody entries. It recomputes every digest before accepting the signature.

In [23]:
verification = lab.verify_audit_pack(
    pack, public_key=signer.public_key(), agents=[claims], results=results,
    artifacts=store.artifacts.values(), custody=custody,
)
assert verification == (True, "verified")
verification

(True, 'verified')

## 17. Failure injection: artifact and custody truncation

The manifest's artifact count/set and terminal custody root expose truncation that a hash chain alone cannot prove.

In [24]:
artifact_attack = lab.verify_audit_pack(
    pack, public_key=signer.public_key(), agents=[claims], results=results,
    artifacts=list(store.artifacts.values())[:-1], custody=custody,
)
custody_attack = lab.verify_audit_pack(
    pack, public_key=signer.public_key(), agents=[claims], results=results,
    artifacts=store.artifacts.values(), custody=custody[:-1],
)
artifact_attack, custody_attack

((False, 'artifact-set-mismatch'), (False, 'custody-mismatch'))

## 18. Produce an OSCAL-shaped assessment result

This subset demonstrates stable IDs, metadata, observations, subjects, methods, evidence references, and policy versions. It is intentionally not presented as complete OSCAL conformance.

In [25]:
oscal = lab.oscal_assessment_results(pack, results)
root = oscal["assessment-results"]
{"oscal_version": root["metadata"]["oscal-version"], "observations": len(root["results"][0]["observations"]), "first": root["results"][0]["observations"][0]}

{'oscal_version': '1.2.3',
 'observations': 7,
 'first': {'uuid': '0154b157d0b8b9b137432de570f476b8',
  'description': 'registered',
  'methods': ['EXAMINE'],
  'collected': '2026-10-28T12:00:00+00:00',
  'subjects': [{'subject-uuid': 'agent:claims', 'type': 'component'}],
  'relevant-evidence': [{'href': 'urn:northstar:evidence:ev-claims-1'}],
  'props': [{'name': 'status', 'value': 'pass'},
   {'name': 'policy-version', 'value': 'northstar-agent-identity-2026.10'}]}}

## 19. Evaluate the full adversarial suite

The population contains compliant, failed, excepted, missing, stale, forged, replayed, cross-tenant, tampered, delegated, least-privilege, and offboarding cases. Exact classification matters because `block` and `review` are operationally different.

In [26]:
report = lab.evaluation()
assert report["hardened"]["exact"] == 18
assert report["hardened"]["false_passes"] == 0
assert report["release_gate"] is True
pd.DataFrame(report["rows"]), {"baseline": report["baseline"], "hardened": report["hardened"], "gate": report["release_gate"]}

(   case_id expected baseline hardened
 0      C01  release  release  release
 1      C02  release  release  release
 2      C03  release  release  release
 3      C04    block    block    block
 4      C05    block    block    block
 5      C06    block    block    block
 6      C07    block  release    block
 7      C08    block  release    block
 8      C09  release  release  release
 9      C10   review  release   review
 10     C11   review  release   review
 11     C12   review  release   review
 12     C13   review  release   review
 13     C14   review  release   review
 14     C15   review    block   review
 15     C16    block    block    block
 16     C17    block    block    block
 17     C18   review  release   review,
 {'baseline': {'exact': 9,
   'total': 18,
   'accuracy': 0.5,
   'false_passes': 8,
   'false_blocks': 0},
  'hardened': {'exact': 18,
   'total': 18,
   'accuracy': 1.0,
   'false_passes': 0,
   'false_blocks': 0},
  'gate': True})

## 20. Production upgrade decisions

| Teaching component | Production direction |
|---|---|
| Deterministic local keys | Authorized KMS/HSM signers, rotation, revocation, and certificate/workload identity |
| In-memory evidence store | Tenant-isolated immutable storage, access logging, retention, backup, and legal hold |
| Python allowlists | Authenticated workload identity and centrally governed producer authorization |
| Local scheduled evaluation | Idempotent workers, checkpoints, retry/reconciliation, SLOs, and alert ownership |
| OSCAL-shaped subset | Official OSCAL 1.2.3 schemas, profile resolution, back matter, and interoperability tests |
| Fixed release gate | Versioned risk acceptance, approval receipts, change control, overrides, monitoring, and rollback |

## Exercises

1. Add a third-party-agent control requiring a current contract, federated identity record, offboarding test, and incident-notification evidence. Inject one stale artifact.
2. Implement a single-use exception approval receipt bound to the exact result digest. Test replay and concurrent consumption.
3. Compare random and risk-weighted sampling across 1,000 synthetic agents. Report critical coverage and selection bias.
4. Extend the OSCAL-shaped export, then validate it against official OSCAL 1.2.3 tooling. Document every gap rather than claiming conformance.
5. Design a multi-region evidence pipeline that preserves source authority, ordering semantics, legal hold, and independent verification during an outage.

## Review questions

- Why is a valid signature insufficient when evidence is stale or from the wrong authoritative source?
- Why must `indeterminate` and `exception` remain distinct from both pass and fail?
- What does a custody hash chain prove, and what requires an externally bound terminal checkpoint?
- Which denominators are required to interpret evidence completeness and sample coverage?
- Where should legal, audit, security, platform, and application owners divide responsibility?

## Reflection

Identify one assurance claim in your environment whose evidence source, freshness limit, or completeness denominator is currently implicit. What decision could be falsely released as a result?

## Summary

Defensible assurance is a chain: versioned requirement → scoped subject → authoritative evidence → deterministic assessment → explicit exception semantics → custody and retention → signed complete manifest → independent verification. A dashboard is only a view over that chain.