# Advanced 12 capstone lab — one identity transaction, end to end

You are the platform security engineer for **Northstar Insurance**. An autonomous claims orchestrator must update claim `8842`, request a bounded payment, call protected tools, and leave defensible evidence. Every trusted fact must come from a control-plane boundary—not from model text.

This notebook imports the tested implementation in `lab.py`. It runs offline and uses deterministic course time so failures are reproducible.

## Learning contract

You will compare a weak baseline with a hardened architecture; bind human, agent, workload, task, delegation, token, policy, approval, and effect; inject failures; and release only when evaluation and evidence gates pass.

**Success:** 17/17 labelled cases correct, zero false allows, zero approval bypasses, a valid signed evidence checkpoint, and a passing compliance gate.

In [1]:
# Canonical course implementation: lab.py
from datetime import timedelta
import json
from pathlib import Path

import pandas as pd
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from lab import (
    CASES, NOW, ApprovalAuthority, AuthorizationEngine, CapabilityToken,
    ContainmentAction, DecisionOutcome, EffectStore, FederationEvidence,
    IncidentResponder, SecurityAlert, TokenBroker, attenuate,
    build_evidence_chain, compliance_gate, containment_plan, evaluate,
    evaluate_baseline, fixture, recovery_ready, redact, run_case,
    sign_checkpoint, telemetry_event, verify_evidence,
)
print(f"Course clock: {NOW.isoformat()}")

Course clock: 2026-10-28T12:00:00+00:00

## 1. Scenario and trusted context

Alice authenticated with OIDC and WebAuthn. The workflow service—not the prompt—constructs a security context. The registry maps the logical agent to one approved SPIFFE-shaped workload. The task service supplies the stable task and operation identifiers.

In [2]:
values = fixture()
context = values["context"]
intent = values["intent"]
pd.DataFrame([
    {"layer": "human", "identity": context.principal_id, "source": "enterprise IdP"},
    {"layer": "agent", "identity": context.agent_id, "source": "agent registry"},
    {"layer": "workload", "identity": context.workload_id, "source": "workload attestation"},
    {"layer": "task", "identity": context.task_id, "source": "workflow service"},
    {"layer": "operation", "identity": context.operation_id, "source": "PEP"},
])

,layer,identity,source
0,human,user:alice,enterprise IdP
1,agent,agent:claims-orchestrator,agent registry
2,workload,spiffe://corp.example/prod/claims-orchestrator,workload attestation
3,task,task:claim-8842,workflow service
4,operation,op:claim-8842:7,PEP

### Invariant

The model may propose `Intent.parameters`; it cannot populate `SecurityContext`. A prompt that says “I am the CFO” is untrusted content, not authentication evidence.

In [3]:
spoof_result = run_case("prompt_identity_spoof")
assert spoof_result == "deny"
spoof_result

'deny'

## 2. Measure the unsafe baseline first

The comparator treats token presence as authority. This is useful because a hardened system should improve a measured failure mode, not merely look more elaborate.

In [4]:
baseline = evaluate_baseline()
{key: value for key, value in baseline.items() if key != "results"}

{'total': 17, 'correct': 3, 'false_allow': 14}

The baseline ignores tenant, lifecycle, workload, relationship, risk, audience, sender, revocation, and federation state. Its false allows are security failures, even if the downstream API happens to reject some of them.

## 3. Audience-, scope-, lifetime-, and sender-bound token exchange

The protected MCP resource must validate the token for itself. The gateway must not pass a client token through to another API. Sender binding makes a copied bearer value insufficient by itself.

In [5]:
root = CapabilityToken(
    token_id="tok_root", tenant_id="northstar", subject="user:alice",
    actor_chain=("agent:claims-orchestrator",), audience="mcp:claims",
    scopes=frozenset({"claim.read", "claim.update", "payment.create"}),
    sender_key_thumbprint="key:claims-workload",
    issued_at=NOW - timedelta(minutes=2), expires_at=NOW + timedelta(minutes=10),
)
broker = TokenBroker()
research_token = broker.exchange(
    root, actor="agent:research", audience="mcp:policy-search",
    scopes={"claim.read"}, sender_key_thumbprint="key:research-workload",
    expires_at=NOW + timedelta(minutes=3),
)
research_token.model_dump(mode="json")

{'token_id': 'tok_e29ff7f236dcdfdc',
 'tenant_id': 'northstar',
 'subject': 'user:alice',
 'actor_chain': ['agent:claims-orchestrator', 'agent:research'],
 'audience': 'mcp:policy-search',
 'scopes': ['claim.read'],
 'sender_key_thumbprint': 'key:research-workload',
 'issued_at': '2026-10-28T11:58:00Z',
 'expires_at': '2026-10-28T12:03:00Z',
 'parent_token_id': 'tok_root'}

In [6]:
broker.verify(
    research_token, tenant_id="northstar", audience="mcp:policy-search",
    action="claim.read", sender_key_thumbprint="key:research-workload", now=NOW,
)
try:
    broker.verify(
        research_token, tenant_id="northstar", audience="mcp:claims",
        action="claim.read", sender_key_thumbprint="key:attacker", now=NOW,
    )
except PermissionError as error:
    print(f"Fail closed: {error}")

Fail closed: TOKEN_AUDIENCE

## 4. Registry, workload, delegation, and relationship composition

No single plane grants authority. The decision requires an active versioned agent, an approved fresh workload, a current attenuated delegation, and an assignment relationship for the claim.

In [7]:
engine = AuthorizationEngine()
decision = engine.decide(**values, now=NOW)
decision.model_dump(mode="json")

{'decision_id': 'dec_631f9d346b8f47a4',
 'outcome': 'allow',
 'reason_codes': ['POLICY_MATCH'],
 'request_digest': '1cac39b2f703eddc050b433f95e028b0067eee9eb1749e8e2e57a3df99c435b0',
 'policy_version': 'claims-2026-10-28.1',
 'expires_at': '2026-10-28T12:00:30Z',
 'constraints': {'allowed_fields': ['notes', 'status'], 'resource_version': 7},
 'obligations': ['emit_decision_event', 'record_effect_receipt'],
 'evidence_ids': ['att_51a8f', 'dlg_claim_8842']}

In [8]:
assert decision.outcome == DecisionOutcome.ALLOW
assert decision.request_digest == intent.request_digest
assert decision.policy_version == engine.policy_version
assert {"allowed_fields", "resource_version"} <= decision.constraints.keys()

### AuthZEN-style boundary

AuthZEN standardizes the PEP/PDP API; OPA, Cedar, or a relationship engine can sit behind it. The rich course decision also carries request digest, policy version, expiry, constraints, obligations, and evidence identifiers because an `ALLOW` boolean alone is not an execution contract.

In [9]:
authzen_request = {
    "subject": {"type": "agent", "id": context.agent_id, "tenant_id": context.tenant_id, "workload_id": context.workload_id},
    "action": {"name": intent.action},
    "resource": {"type": "claim", "id": intent.resource, "tenant_id": context.tenant_id},
    "context": {
        "principal_id": context.principal_id, "task_id": context.task_id,
        "operation_id": context.operation_id, "purpose": intent.purpose,
        "tool": intent.tool, "delegation_id": values["delegation"].delegation_id,
        "risk": "low",
    },
}
authzen_request

{'subject': {'type': 'agent',
  'id': 'agent:claims-orchestrator',
  'tenant_id': 'northstar',
  'workload_id': 'spiffe://corp.example/prod/claims-orchestrator'},
 'action': {'name': 'claim.update'},
 'resource': {'type': 'claim', 'id': 'claim:8842', 'tenant_id': 'northstar'},
 'context': {'principal_id': 'user:alice',
  'task_id': 'task:claim-8842',
  'operation_id': 'op:claim-8842:7',
  'purpose': 'claims_adjustment',
  'tool': 'mcp:claims',
  'delegation_id': 'dlg_claim_8842',
  'risk': 'low'}}

## 5. PEP enforcement and effect evidence

The PEP verifies decision binding and expiry, enforces field constraints, uses a stable logical operation ID, and records an effect receipt. A duplicate call returns the same receipt; it does not repeat the write.

In [10]:
store = EffectStore()
first = store.execute(context=context, intent=intent, decision=decision, now=NOW)
retry = store.execute(context=context, intent=intent, decision=decision, now=NOW)
assert first == retry
first.model_dump()

{'operation_id': 'op:claim-8842:7',
 'request_digest': '1cac39b2f703eddc050b433f95e028b0067eee9eb1749e8e2e57a3df99c435b0',
 'decision_id': 'dec_631f9d346b8f47a4',
 'effect': 'claim.update:claim:8842',
 'resource_version': 7}

### Unknown outcome is not a retry signal

If the effect committed but the response was lost, the workflow must reconcile the same operation and request digest before making another change.

In [11]:
unknown_values = fixture(parameters={"status": "closed"})
unknown_values["context"] = unknown_values["context"].model_copy(update={"operation_id": "op:claim-8842:8"})
unknown_decision = engine.decide(**unknown_values, now=NOW)
try:
    store.execute(
        context=unknown_values["context"], intent=unknown_values["intent"],
        decision=unknown_decision, now=NOW, simulate_lost_response=True,
    )
except TimeoutError as error:
    print(error)
reconciled = store.reconcile(
    unknown_values["context"].operation_id, unknown_values["intent"].request_digest
)
assert reconciled is not None
reconciled

OUTCOME_UNKNOWN_RECONCILE

EffectReceipt(operation_id='op:claim-8842:8', request_digest='2f2122aa8ca09ec9bbb0ba260e1cd61625966b8ff876ea35c0604d5ecc4a852b', decision_id='dec_9a80df259749a96e', effect='claim.update:claim:8842', resource_version=7)

## 6. High-risk payment: signed, exact, single-use approval

A high-risk decision remains non-executable. A supervisor receipt binds tenant, human, agent, exact intent digest, policy version, role, lifetime, and nonce. The PDP then evaluates the new evidence and issues a new decision.

In [12]:
payment = fixture(action="payment.create", parameters={"amount": 1200, "currency": "USD"})
payment["intent"] = payment["intent"].model_copy(update={"tool": "mcp:payments"})
payment_decision = engine.decide(**payment, now=NOW)
assert payment_decision.outcome == DecisionOutcome.APPROVAL_REQUIRED
payment_decision.reason_codes

('HUMAN_APPROVAL_REQUIRED',)

In [13]:
approval_authority = ApprovalAuthority()
approval = approval_authority.issue(
    context=payment["context"], intent=payment["intent"], policy_version=engine.policy_version,
    approver_id="user:supervisor", approver_role="claims-supervisor", now=NOW,
)
approved_decision = engine.approve(
    payment_decision, authority=approval_authority, receipt=approval,
    context=payment["context"], intent=payment["intent"], now=NOW,
)
assert approved_decision.outcome == DecisionOutcome.ALLOW
approved_decision.model_dump(mode="json")

{'decision_id': 'dec_1699c64390ea8a70',
 'outcome': 'allow',
 'reason_codes': ['APPROVAL_VERIFIED'],
 'request_digest': '343c0b4b4f70d95ace23c9e10d250495d619cd181aea61ad3d32de31f8ed5d33',
 'policy_version': 'claims-2026-10-28.1',
 'expires_at': '2026-10-28T12:00:30Z',
 'constraints': {'maximum_amount': 5000, 'currency': 'USD'},
 'obligations': ['emit_decision_event', 'record_effect_receipt'],
 'evidence_ids': ['att_51a8f', 'dlg_claim_8842', 'apr_cf0d48bc04ccc8d6']}

In [14]:
try:
    engine.approve(
        payment_decision, authority=approval_authority, receipt=approval,
        context=payment["context"], intent=payment["intent"], now=NOW,
    )
except PermissionError as error:
    print(f"Replay blocked: {error}")

Replay blocked: APPROVAL_REPLAY

In [15]:
payment_effect = EffectStore().execute(
    context=payment["context"], intent=payment["intent"],
    decision=approved_decision, now=NOW,
)
payment_effect.model_dump()

{'operation_id': 'op:claim-8842:7',
 'request_digest': '343c0b4b4f70d95ace23c9e10d250495d619cd181aea61ad3d32de31f8ed5d33',
 'decision_id': 'dec_1699c64390ea8a70',
 'effect': 'payment.create:claim:8842',
 'resource_version': 8}

## 7. Authorization before RAG, memory, MCP, and federation

Discovery or retrieval is not a grant. Bind the intended tool in the decision, authorize before fetching, filter by authorized resources, and authorize again before using retrieved content for a consequential effect. A partner's valid identity is intersected with local trust-anchor, freshness, and action policy.

In [16]:
federation = FederationEvidence(
    issuer="https://partner.example", subject="agent:external-research",
    trust_anchor="https://federation.corp.example", metadata_digest="sha256:partner-demo",
    fetched_at=NOW, allowed_actions=frozenset({"knowledge.search"}),
    requested_action="knowledge.search",
)
federation.verify(NOW)
print("Federated identity authenticated; local resource authorization is still required.")

Federated identity authenticated; local resource authorization is still required.

## 8. Privacy-safe correlated telemetry

Identity telemetry records trace, task, operation, decision, policy, and evidence correlation. Recursive redaction removes nested credentials and keyed pseudonymization avoids exposing the direct principal identifier.

In [17]:
event = telemetry_event(
    "authorization.decision", trace_id="trace-8842", context=context, decision=decision,
    details={"nested": {"authorization": "Bearer do-not-export"}, "outcome": decision.outcome},
)
assert "do-not-export" not in json.dumps(event)
event

{'schema': 'agent.identity.event/2.0',
 'event_type': 'authorization.decision',
 'timestamp': '2026-10-28T12:00:00+00:00',
 'trace_id': 'trace-8842',
 'tenant_id': 'northstar',
 'principal_id': 'hmac:9ba7928199f88d54537c',
 'agent_id': 'agent:claims-orchestrator',
 'workload_id': 'spiffe://corp.example/prod/claims-orchestrator',
 'task_id': 'task:claim-8842',
 'operation_id': 'op:claim-8842:7',
 'decision_id': 'dec_631f9d346b8f47a4',
 'policy_version': 'claims-2026-10-28.1',
 'evidence_ids': ['att_51a8f', 'dlg_claim_8842'],
 'details': {'nested': {'authorization': '[REDACTED]'},
  'outcome': <DecisionOutcome.ALLOW: 'allow'>}}

## 9. Incident response and governed recovery

An alert signature or producer identity does not grant authority over every event type. The responder admits only governed producer/event pairs. Destructive containment needs approval, actions are idempotent, and recovery is conjunctive.

In [18]:
alert = SecurityAlert(
    finding_id="finding:stolen-token-1", producer="siem:identity",
    event_type="stolen_token", token_id="tok_root", agent_id=context.agent_id,
)
responder = IncidentResponder()
responder.admit(alert)
plan = containment_plan(alert.finding_id, alert.token_id, alert.agent_id)
[action.model_dump() for action in plan]

[{'action_id': 'act_190bee55d84e',
  'finding_id': 'finding:stolen-token-1',
  'action': 'revoke_token',
  'target': 'tok_root',
  'destructive': False},
 {'action_id': 'act_75e5026949f9',
  'finding_id': 'finding:stolen-token-1',
  'action': 'quarantine_agent',
  'target': 'agent:claims-orchestrator',
  'destructive': True}]

In [19]:
response_receipts = [
    responder.execute(action, destructive_approval=action.destructive) for action in plan
]
recovery = {
    "credential_rotated": True, "fresh_attestation": True,
    "persistence_removed": True, "incident_cleared": True, "approved": True,
}
assert recovery_ready(recovery)
response_receipts

['response:revoke_token:tok_root:act_190bee55d84e',
 'response:quarantine_agent:agent:claims-orchestrator:act_75e5026949f9']

## 10. Tamper evidence plus completeness evidence

A hash chain detects edits relative to a trusted head, but a valid prefix can survive suffix deletion. The independent Ed25519 checkpoint binds both the expected event count and terminal root.

In [20]:
events = [
    event,
    {"event_type": "effect.receipt", **first.model_dump()},
    {"event_type": "incident.response", "receipts": response_receipts},
]
chain = build_evidence_chain(events)
evidence_key = Ed25519PrivateKey.generate()
checkpoint = sign_checkpoint(chain, evidence_key)
assert verify_evidence(chain, checkpoint, evidence_key.public_key())
checkpoint.model_dump()

{'count': 3,
 'root_hash': '7cd968180021ce10856df5e9cd27448bc07bfa5b8611ad769b7377e4a8245729',
 'signature': 'll3CCSud7MVYdQCfe8efVOclXA7kj1LFtrdopDLmuf5OIVTqr22GNaFSwPRIK-xKBC8dmNMYHTi9MaQ2lxMPAg=='}

In [21]:
assert not verify_evidence(chain[:-1], checkpoint, evidence_key.public_key())
print("Suffix truncation detected by independently signed count and root.")

Suffix truncation detected by independently signed count and root.

## 11. Failure injection and adversarial evaluation

The matrix varies one trust assumption at a time: tenant, lifecycle, workload, attestation freshness, delegation, relationship, risk, audience, sender, token status, prompt identity, federation freshness, and trust anchor.

In [22]:
hardened = evaluate()
evaluation_rows = [
    {"case": name, "expected": expected, "actual": hardened["results"][name],
     "pass": expected == hardened["results"][name]}
    for name, expected in CASES.items()
]
pd.DataFrame(evaluation_rows)

                      case           expected             actual  pass
0            normal_update              allow              allow  True
1    prompt_identity_spoof               deny               deny  True
2             cross_tenant               deny               deny  True
3           inactive_agent               deny               deny  True
4           wrong_workload               deny               deny  True
5        stale_attestation               deny               deny  True
6       expired_delegation               deny               deny  True
7   wrong_delegation_scope               deny               deny  True
8     missing_relationship               deny               deny  True
9            critical_risk               deny               deny  True
10               high_risk  approval_required  approval_required  True
11          wrong_audience               deny               deny  True
12            wrong_sender               deny               deny  True
13           revoked_token               deny               deny  True
14           expired_token               deny               deny  True
15        stale_federation               deny               deny  True
16        untrusted_anchor               deny               deny  True

In [23]:
summary = {
    "baseline_correct": baseline["correct"],
    "baseline_false_allow": baseline["false_allow"],
    "hardened_correct": hardened["correct"],
    "hardened_total": hardened["total"],
    "hardened_false_allow": hardened["false_allow"],
    "hardened_false_deny": hardened["false_deny"],
    "approval_bypass": hardened["approval_bypass"],
}
summary

{'baseline_correct': 3,
 'baseline_false_allow': 14,
 'hardened_correct': 17,
 'hardened_total': 17,
 'hardened_false_allow': 0,
 'hardened_false_deny': 0,
 'approval_bypass': 0}

In [24]:
assert hardened["correct"] == hardened["total"] == 17
assert hardened["false_allow"] == 0
assert hardened["approval_bypass"] == 0
assert baseline["false_allow"] > 0

## 12. Evidence-backed release gate

Configured controls are not enough. Release requires the inventory, decision, effect receipt, minimized telemetry, signed completeness checkpoint, and safe evaluation report.

In [25]:
artifacts = {
    "agent_inventory": values["agent"].model_dump(mode="json"),
    "authorization_decision": decision.model_dump(mode="json"),
    "effect_receipt": first.model_dump(mode="json"),
    "telemetry_event": event,
    "signed_checkpoint": checkpoint.model_dump(),
    "evaluation_report": hardened,
}
release, findings = compliance_gate(artifacts)
assert release and not findings
{"release": release, "findings": findings}

{'release': True, 'findings': ()}

## Reflection

1. Which control prevents a valid token from becoming universal authority?
2. Why must approval produce a new decision instead of changing the old result?
3. Which receipt proves the external effect, and which component is independent enough to trust it?
4. What state must be rechecked immediately before an irreversible action?
5. Which failures should be `deny`, which should be `approval_required`, and which operational failures need a distinct retry/review state?
6. What production component would replace each course adapter without changing its contract?

## Production upgrade path

Replace the in-memory registry and receipt stores with transactional, durable services; the course token with an enterprise authorization server and sender-constrained OAuth; the workload fixture with SPIRE; the engine adapters with binary-validated OPA/Cedar/OpenFGA deployments behind an AuthZEN boundary; local keys with governed KMS/HSM custody; and the debug telemetry path with access-controlled OpenTelemetry pipelines. Add availability objectives, revocation propagation measurements, key rotation, chaos tests, and vendor conformance suites.

Do not remove request digests, policy versions, exact approval binding, idempotency, reconciliation, signed checkpoints, or the adversarial release gate during that migration.